version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - vault-network
    volumes:
      - mongodb-data:/data/db
    ports:
      - "27017:27017"
    restart: unless-stopped

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vault-backend
    depends_on:
      - mongodb
    networks:
      - vault-network
    ports:
      - "3000:3000"
    env_file:
      - .env
    stdin_open: true
    tty: true
    restart: unless-stopped

networks:
  vault-network:
    driver: bridge

volumes:
  mongodb-data:
    driver: local
